{"content": "As there is a thrown exception at line 5, the line 6 is not executed, but the exception is caught by the catch statement so the catch block is executed. The following code is also executed. Note that the catch statement takes an exception as parameter. There is a third case: when the exception is not from the same class as the parameter:\n", "stemmed": "As thrown except line 5 , line 6 execut , except caught catch statement catch block execut . the follow code also execut . note catch statement take except paramet . there third case : except class paramet :", "link": "https://en.wikibooks.org/wiki/Java_Programming/Throwing_and_Catching_Exceptions"}